sources:
  reddit:
    - name: "r/ralsei"
      url: "https://www.reddit.com/r/ralsei/"
      weight: 5
    - name: "r/Deltarune"
      url: "https://www.reddit.com/r/Deltarune/"
      weight: 2
    - name: "r/undertale"
      url: "https://www.reddit.com/r/Undertale/"
      weight: 1
  twitter:
    - name: "Bi-Hourly Ralsei"
      url: "https://x.com/bihourlyralsei"
      weight: 5
      
settings: 
  default:
    user-agent: "ralseibot (https://github.com/BananaJeanss/ralseibot)"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    timeout-ms: 5000
    max-retries: 3